### PR TITLE
fix support for view compat for setPivot in reset method

### PR DESCRIPTION
**Pull request by lolevsky**

### CODE REVIEW

**Comment by Knight704** [comment]
i guess this fix would allow to use this library with minsdk 10

**Comment by wasabeef** [comment]
@lolevsky @Knight704 

Hey.
It worked flawlessly?

**Comment by Knight704** [comment]
why not?

**Comment by wasabeef** [comment]
@Knight704 

Using ObjectAnimator in adapter.

**Comment by wasabeef** [comment]
@lolevsky @lolevsky 

" Issue 80863:	ViewCompat.setPivotY should call IMPL.setPivotY"
https://code.google.com/p/android/issues/detail?id=80863

**Pull request closed without merging**
