### PR TITLE
Fixing #64 issue that we faced in special case

### PR DESCRIPTION
**Pull request by emartynov**
We faced `IndexOutOfBoundException` because we remove animator at the end of the animation. This small change checks size before removing.

Please review and comment!

### CODE REVIEW

**Comment by wasabeef** [comment]
@emartynov 

Thanks.
Let me confirm.

**Comment by emartynov** [comment]
Please wait until I fix the Travis build

**Comment by emartynov** [comment]
And now I'm completely lost since on my local environment I don't have lint warnings anymore

**Comment by emartynov** [comment]
An answer from SO http://stackoverflow.com/questions/34942840/lint-error-do-not-treat-position-as-fixed-only-use-immediately

**Comment by emartynov** [comment]
Do you have linux machine? Can you check why lint is failing?

**Comment by emartynov** [comment]
Please also check my solution for holder and animation starting when bind is happening

**Comment by wasabeef** [comment]
@emartynov 
Thank you
2.2.0 released :shipit:

**Pull request merged**
